### ISSUE TITLE
Hosting Dockerfile in brainlife/cli

### ISSUE THREAD

**Issue by soichih** [brainlife/bl-cli-docker#2]
@bacaron Would it be okay if I move the Dockerfile to brainlife/cli? I think it makes more sense if we maintain both the CLI code and Dockerfile as they should be released together most of the time.

I just created the Dockerfile here
> https://github.com/brainlife/cli
I've also simplified the Dockerfile.. I don't think we need jq inside this container?

**Comment by bacaron** [comment]
Of course! Yeah I just made this cause I wasn't exactly sure where to put it.
